name: Continuous Deployment
on: 
  push:
  pull_request:
jobs:
  test:
      name: Test
      runs-on: ubuntu-18.04
      steps:
      - name: Checkout
        uses: actions/checkout@v1

      - uses: actions/setup-node@v1.1.0
        with:
          node-version: '12.x'
    
      - name: Cache Node Modules
        uses: actions/cache@v1
        with:
          path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
          
      - name: Cache Cypress
        uses: actions/cache@v1
        with:
          path: ~/.cache/Cypress # npm cache files are stored in `~/.npm` on Linux/macOS
          key: ${{ runner.os }}-cypress-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-cypress-

      - run: npm install
      - run: npm run lint
      - run: npm run test.ci
      - run: npx nyc report --reporter=text-summary

      - name: Archive code coverage results
        uses: actions/upload-artifact@v1
        with:
          name: code-coverage-report
          path: coverage
